// Generated by CoffeeScript 1.10.0
(function() {
  var Account, BinaryFile, LocalStrategy, app, bodyParser, cookieParser, express, favicon, logger, mongoose, passport, path, routes, users;

  express = require('express');

  path = require('path');

  logger = require('morgan');

  bodyParser = require('body-parser');

  mongoose = require('mongoose');

  routes = require('./routes/index');

  fs = require('fs');

  app = express();

  app.set('views', path.join(__dirname, 'views'));

  app.set('view engine', 'jade');

  app.use(logger('dev'));

  app.use(bodyParser.json());

  app.use(bodyParser.urlencoded({
    extended: false
  }));

  app.use(express["static"](path.join(__dirname, '/public')));

  app.use('/', routes);

  mongoose.Promise = global.Promise;

  if(process.env.NODE_ENV == 'test')
    mongoose.connect('mongodb://localhost/test');
  else
    mongoose.connect('mongodb://localhost/dev', function(err){
      if(err) console.log(err);
    });

  mongoose.set('debug', true);
  app.use(function(req, res, next) {
    var err;
    err = new Error('Not Found');
    err.status = 404;
    return next(err);
  });
  app.use(function(req, res, next) {
    res.setHeader('Last-Modified', (new Date()).toUTCString());
    next();    
  });
  app.disable('etag');

  var bodyParser = require('body-parser');
  app.use(bodyParser.json()); // support json encoded bodies
  app.use(bodyParser.urlencoded({ extended: true })); // support encoded bodies

  if (app.get('env') === 'development') {
    app.use(function(err, req, res, next) {
      console.log(err);
      res.status(err.status || 500);
      return res.render('error', {
        message: err.message,
        error: err
      });
    });
  }

  app.use(function(err, req, res, next) {
    res.status(err.status || 500);
    return res.render('error', {
      message: err.message,
      error: {}
    });
  });

  module.exports = app;

}).call(this);
